services:
  postal:
    image: ghcr.io/postalserver/postal:latest
    platform: linux/amd64
    container_name: postal
    # restart: unless-stopped
    depends_on:
      - mysql
    ports: 
      - 1025:1025
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/postal
      TZ: Asia/Bangkok
      DEBUG: "*"
    volumes:
      - postal_data:/app/data
    command: 
       sh -c "until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done; \
             postal initialize && postal smtp-server & postal web-server & postal worker"

      # sh -c "until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done;
      #        postal initialize && postal start"
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      # DATABASE_URL: mysql://root:root@mysql:3306/mysql
      MYSQL_ROOT_PASSWORD: root  # ตั้งรหัสผ่านสำหรับ root
      MYSQL_DATABASE: postal
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - postal_net

volumes:
  mysql_data:
  postal_data:

networks:
  postal_net:
    driver: bridge
